#!/bin/bash

echo "Note: Use this to test your submission in an otherwise EMPTY directory that only contains your .tgz"

#test 1 archive present
if [ ! -f ./prog4.tgz ]; then
    echo "Project 4 archive (prog4.tgz) not found in current directory. Submission will not be graded."
    exit 1
fi

gtar zxf prog4.tgz

#test 2 make all
(make all) >/dev/null
made=$?
if [ "$made" -ne "0" ]; then
	echo -e "Make all returned an error. Submission will not be graded."
	exit 1
fi

#test 3 s-tee present
if [ ! -f ./s-tee ]; then
    echo " Program named s-tee not generated by make. Submission will not be graded."
    exit 1
fi

#test 4 readme present
if [ ! -f ./README ]; then
    echo "File named README not present. (Please name your readme \"README\")"
    exit 1
fi

echo "Submission will be graded successfully. Please be aware this does not test your submission for functionality, only that the autograder will run successfully."
